### ISSUE TITLE
Log level for non-matching rules (info to debug)

### ISSUE THREAD

**Issue by palmerabollo** [HotelsDotCom/kube-graffiti#2]
I think that logs about rules that don't match should be changed to DEBUG level (currently INFO, see example below) because otherwise kube-graffiti's output is too verbose in environments with many kubernetes objects.

> 2019-04-09T10:35:37Z |**INFO**| rule didn't match - not painting object component=grafitti rule=add-toleration-to-pods

What do you think?

**Comment by davidmccormick** [comment]
Good idea!  I've reduced the logs in a new 0.8.4 release!
